### ISSUE TITLE
Is it possible to find which mutational signature a SNV belongs to?

### ISSUE THREAD

**Issue by lincj1994** [AlexandrovLab/SigProfilerExtractor#126]
Hi. Thanks for developing such a suite of powerful tools of SigProfiler.
I'm wondering if it is possible to find which mutational signature contribute to a specific SNV in the input data. I think it may be feasible since SigProfiler returns COSMIC_SBS96_Activities_refit.txt, which tells the COSMIC signatures that compose the mutations of each sample. But I dont know how.
Another question is if the sample size matters when using the SigProfiler tools, including the Extractor and SingleSample.
Lin.

**Comment by marcos-diazg** [comment]
Dear @lincj1994, thanks for your interest! SigProfilerExtractor provides you with the probability of every mutational channel to be caused by each of your extracted _de novo_ signatures, not those for specific mutations. You can find this information in the `De_Novo_Mutation_Probabilities` file inside the `De-Novo_Solution/Activities` folder.

The COSMIC refitting activities you mentioned are generated after decomposing your _de novo_ extracted signatures into COSMIC signatures and then assigning mutations to this subset of COSMIC signatures.

Sample size has an important role in extracting signatures with SigProfilerExtractor. However, it doesn't affect signature assignment as this is done on a sample-by-sample basis.

I strongly recommend checking our most recent SigProfilerExtractor publication at https://www.biorxiv.org/content/10.1101/2020.12.13.422570v3, for in-depth details about the methodology. Please feel free to reopen the ticket if you find any additional technical problems with the tools.
