### ISSUE TITLE
How can I load my specific reference genome? (Pig)

### ISSUE THREAD

**Issue by jingydz** [AlexandrovLab/SigProfilerExtractor#127]
Hi, thank you develop this software.
I wonder how can I load my specific reference genome to analyze it?
On this website,(https://osf.io/s93d5/wiki/7.%20Currently%20Supported%20Genomes/) I find the species currently supported by SigProfiler, but I want to analyze other species, like pig?
How do I load the pig reference genome and use it to analyze my data?
Thanks in advance!
![image](https://user-images.githubusercontent.com/45711930/168482331-6f6da0dd-aeb9-4d5a-a48e-ea608f75658b.png)

**Comment by marcos-diazg** [comment]
Hi @jingydz, and thanks for your interest! In order to analyze data from other species, you need to generate your input mutational matrix first. This process is internally managed by SigProfilerMatrixGenerator, so I'd recommend opening an issue about this in its own [GitHub](https://github.com/AlexandrovLab/SigProfilerMatrixGenerator). I'll close this issue here, since SigProfilerExtractor does not control the reference genomes for the generation of mutational matrices, but happy to help if you have any further questions about signature extraction.
