### ISSUE TITLE
DBS78A de novo signature tallied separately even though 100% COSMIC DBS4

### ISSUE THREAD

**Issue by toddajohnson** [AlexandrovLab/SigProfilerExtractor#128]
The DBS78_Decomposition_Plots.pdf has two de novo signatures DBS78A and DBS78B.  DBS78A decomposed 100% to COSMIC DBS4, while DBS78B decomposed into 25.02% DBS4 23.94% DBS9, 22.44% DBS11, 16.58% DBS6, and 12.02% DBS2.  Strangely, in the refit activities plot (COSMIC_DBS78_Activity_Plots_refit.pdf), the bars include both the COSMIC DBS4 and the de novo DBS78A.  Shouldn't those have been merged into just DBS4?

Thank you for producing such a useful tool!

**Comment by marcos-diazg** [comment]
Dear @toddajohnson,

Thanks so much for your interest! The inclusion of _de novo_ DBS78A into the refit activities is linked to the fact that this signature was not accurately reconstructed by a combination of COSMIC signatures.

Even though the decomposition plot shows 100% decomposed to COSMIC DBS4, if the cosine similarity is below 0.8 this decomposition is not considered accurate, and the assignment is performed using the _de novo_ signature (in your case, DBS78A). On the other hand, DBS4 is also included in the refit activities because it is part of the DBS78B reconstruction.

I'm closing the issue since this is not a technical problem with the tool, but I'll be happy to continue the discussion about the interpretation of the results over email if that helps (mdiazgay@health.ucsd.edu). Thanks again!
