### ISSUE TITLE
interpretation of the results

### ISSUE THREAD

**Issue by stroke1989** [AlexandrovLab/SigProfilerExtractor#135]
Hi,
I'm a new to this tool. Thanks for this excellent tool. I used this tool to extracted de novo mutational signature from my WES data(40 cases). One  de novo DBS signature was found. When I investigate the activity of this novel DBS signature in my samples,  only 19 samples was shown to harbor this novel DBS? why? does it mean that no DBS events occurred in the remainning samples?
<img width="392" alt="Snipaste_2022-07-11_00-13-58" src="https://user-images.githubusercontent.com/61864553/178152964-478a1ba3-d7d8-418e-b92c-9d4c29f302ce.png">

Hope your reponse! Appreciate!

**Comment by marcos-diazg** [comment]
Hey @stroke1989,

Thanks for your interest in our tool. As you can see in your attached plot, the number of DBS events in your sample is very small (e.g., 15 of your samples have only 1 DBS mutation). So most probably the remaining 21 samples don’t have any DBSs and therefore are not displayed in the plot.

But considering you’re using WES data this is expected as the number of DBSs for some cancer types is very low. This means that the signature analysis will not be reliable for DBSs, as you don’t have enough number of mutations. This is also the reason why you’re getting one single novel signature as the result of your analysis, because you don’t have enough power to identify any of the known DBS signatures (you can check them at https://cancer.sanger.ac.uk/signatures/dbs/).

I hope this helps, and please let us know if you have further questions!
