### ISSUE TITLE
copy number signature extraction - try to decompose to published CNV signature

### ISSUE THREAD

**Issue by ipstone** [AlexandrovLab/SigProfilerExtractor#136]
Congratulations on the new CNV signature paper! https://www.nature.com/articles/s41586-022-04738-6

I would like to extract CNV signatures (decompose to the published CNV signatures to get insights of the tumors) - for which I guess the right tool would be either using https://github.com/AlexandrovLab/SigProfilerSingleSample or SigProfilerExtractor?

Here are my more specific questions:
1. For SigProfileSingleSample, I couldn't find the code to run it with CNV signatures - is there a way to run SigProfileSS using given signatures such as copy number signatures?

2. For SigProfilerExtractor, I know for SNV, the extract signatures will be further decomposed into known/cosmic signatures. Will CNV signatures will be also decomposed? What are the main differences between these 'decomposed' activities vs. results from SigProfileSingleSample?

Thanks a lot!

**Comment by marcos-diazg** [comment]
Dear @ipstone,

Thanks so much for your interest and your kind words! Regarding your questions:

1. If you want to perform mutational signature refitting analysis, we strongly recommend using our new [SigProfilerAssignment](https://github.com/AlexandrovLab/SigProfilerAssignment) tool, since we are in the process of retiring SigProfilerSingleSample. Just make sure to use the latest version of the tool, v0.0.8, which includes support for the current set of reference CNV signatures.

2. In case you want to perform mutational signature _de novo_ extraction and decomposition to COSMIC signatures, SigProfilerExtractor also supports CNV reference signatures.

If you want to learn more about the differences between the two types of analysis (_de novo_ extraction vs. refitting), I would recommend checking the following references: https://doi.org/10.1016/j.mam.2019.05.002 or https://doi.org/10.1093/bib/bbx082.

I hope this helps, and please reopen the ticket if you have further questions.
