### ISSUE TITLE
Using output from SigProfilerMatrixGenerator as input for SigProfilerExtractor

### ISSUE THREAD

**Issue by rsg344** [AlexandrovLab/SigProfilerExtractor#147]
Hi,

I converted my data into the matrices using SigProfilerMatrixGenerator. However, when I try to run SigProfilerExtractor the following error message comes up:
IsADirectoryError: [Errno 21] Is a directory: '/home/ec2-user/mutation_signature/output/vcf_files/SNV'

 I am running it as follows:
sigProfilerExtractor("vcf", "results", "/home/ec2-user/mutation_signature/output/vcf_files/
", reference_genome="GRCh37", minimum_signatures=1, maximum_signatures=10, nmf_replicates=100)

Where inside of my vcf_files folder there are the corresponding directories of DBS, ID, MNS, and SNV as outputted from the matrix generator tool.

I was wondering how do I input the matrices that I got from the matrix generator tool? Obviously the path to my input files is wrong.

Thanks!

**Comment by marcos-diazg** [comment]
Hi @rsg344,

Thanks for your question. As explained in our README, there are two options to run SigProfilerExtractor, depending on the value of the `input_type` parameter. If you set this up to "vcf", the tool expects a directory with one or more files in VCF/MAF/TXT format (any of the [formats accepted in SigProfilerMatrixGenerator](https://osf.io/s93d5/wiki/3.%20Using%20the%20Tool%20-%20Input/)). However, if you set `input_type` to "matrix", SigProfilerExtractor expects a single matrix file generated with SigProfilerMatrixGenerator.

In your specific case, you selected `input_type` as "vcf", so the tool expects a directory with one or more input files. However, you are specifying a folder that contains other folders instead of individual files. There are two possible solutions:

* You can run SigProfilerExtractor directly from your input data (SigProfilerMatrixGenerator will be run automatically as part of SigProfilerExtractor), keeping `input_type` to "vcf".
* You can change `input_type` to "matrix" and set the `input_data` parameter to the specific matrix file you want to use. For example, for the SBS96 matrix, the path should be similar to '/home/ec2-user/mutation_signature/output/SBS/Your-project-name.SBS96.all.

I hope this helps, and feel free to reopen the issue if you have any further questions.

**Comment by rsg344** [comment]
Yes, that worked. Thank you so much!
