### ISSUE TITLE
questions about estimate_solution and results

### ISSUE THREAD

**Issue by thisisliuyu** [AlexandrovLab/SigProfilerExtractor#159]
Hi，
Thanks for developing such wonderful tools.But,I have two little questions.I hope you can help me. 
1.I noticed Extractor can estimate the best solution among different number of solutions. However,I wonder if it is possible to use estimate_solution function  my own data.I just want to know the appropriate number of extracting without a complete run in SigprofilerExtractor.
2.If the optimal number of signatures is 3, In results folder,Are "Suggested_Solution-SBS96_De-Novo_Solution" Folder and "All_Solutions-SBS96_3_Signatures" Folder  the same? In my result folder I noticed SBS96_S3_TMB_NMF_plot.pdf and SBS96_De-Novo_TMB_plot_refit.pdf are different on X-axis.why is that?
Thanks in advance.
[SBS96_De-Novo_TMB_plot_refit.pdf](https://github.com/AlexandrovLab/SigProfilerExtractor/files/9721948/SBS96_De-Novo_TMB_plot_refit.pdf)
[SBS96_S3_TMB_NMF_plot.pdf](https://github.com/AlexandrovLab/SigProfilerExtractor/files/9721971/SBS96_S3_TMB_NMF_plot.pdf)

**Comment by marcos-diazg** [comment]
Hi @thisisliuyu. Thanks for reaching out! Please find below my answers:

1. Unfortunately, you need to do a complete run of SigProfilerExtractor to estimate the best number of signatures for your data, since the tool uses the stability of the different signature solutions for this estimation. If you are concerned about running time, you can try to use a smaller number of `nmf_replicates` for a first run to decide the number of signatures, and then increase that number for a second run with the final number of signatures.

2. When the optimal number of signatures is determined, as you noticed, the `Suggested_Solution` folder is created. The main difference of this folder with respect to the solution found in the `All_Solutions` folder is that the activities have been refitted. This means that [SigProfilerAssignment](https://github.com/AlexandrovLab/SigProfilerAssignment/) has been run in the background, and the contribution of each signature to each individual sample has been re-estimated by using our assignment algorithm. More details can be found in our recent [Cell Genomics publication](https://doi.org/10.1016/j.xgen.2022.100179), as well as in our [wiki page](https://osf.io/t6j7u/wiki/home/).

I hope this helps, and please feel free to reopen the ticket or reach out by email (mdiazgay@health.ucsd.edu) if you have further questions.
