### ISSUE TITLE
Differences in de novo and decomposed solution

### ISSUE THREAD

**Issue by pushpa-itagi** [AlexandrovLab/SigProfilerExtractor#171]
Hi, 

I ran sigProfilerEXtractor for 5 samples and observe three signatures showing up. I had following questions:
1. Can we turn off the discovery mode and only match with existing signatures ?
2. The activities.txt in denovo solution folder and decomposed folder in selected solutions vary a lot. For example in the denovo solution the activities are as follows 
    **_samples	CNV48A	CNV48B	CNV48C
P037Liv1FF	687	0	0
P037Liv2FF	586	0	0
P037Lym1FF	416	66	21
P037PanFF	0	0	379
P037PerFF	536	72	0
P037PriFFPE	0	1727	0_**
 In deconvoluted they are as follows
  **Samples	CN4	CN7	CN20	CNV48A	CNV48C
P037Liv1FF	0	0	0	687	0
P037Liv2FF	0	0	0	586	0
P037Lym1FF	0	0	84	419	0
P037PanFF	0	0	0	0	379
P037PerFF	0	0	0	608	0
P037PriFFPE	406	0	657	664	0**

For example, in sample P037PriFFPE why do we see only CNV48B in denovo and CNV48A and CNV48B in deconvoluted, somehow these activity plots do not match ? Please let me know, I might be missing something fundamental in the extractor method here. 

Thanks

Pushpa

**Comment by marcos-diazg** [comment]
Dear Pushpa,

Thanks for your interest! Regarding your questions:

1. If you prefer to assign known reference signatures to your samples instead of extracting _de novo_ signatures, I recommend you to use our new [SigProfilerAssignment](https://github.com/AlexandrovLab/SigProfilerAssignment/) tool (using cosmic_fit analysis).

2. Decomposed and _de novo_ activities are expected to be different since, in the first case, you are using known reference signatures to reconstruct your samples. In contrast, novel extracted signatures from your data are considered for the _de novo_ activities. Regarding your particular example, CNV48B is decomposed into CN4, CN7 and CNV20. Also, interestingly, it seems that there is no decomposition of reference signatures that can accurately explain your _de novo_ extracted CNV48A and CNV48C signatures. This is why you see CNV48A and CNV48C in both _de novo_ and decomposed activities. You can find more information about the decomposition of _de novo_ signatures in the STAR Methods of our recent publication (https://doi.org/10.1016/j.xgen.2022.100179).

Please feel free to reopen the ticket or reach out by email (mdiazgay@health.ucsd.edu) if you have further questions.
