### ISSUE TITLE
number of signatures in solution

### ISSUE THREAD

**Issue by bakeronit** [AlexandrovLab/SigProfilerExtractor#210]
Hi there,

I am using this to extract signatures from ~100 samples, however, I couldn't decide the number of signatures by the selection plot attached below.
[SBS96_selection_plot.pdf](https://github.com/AlexandrovLab/SigProfilerExtractor/files/11550234/SBS96_selection_plot.pdf)

It suggests 6 is the solution, but I feel 5 might be better. I know that the decision is not simply based on maximising the average stability while minimising the mean sample cosine distance. But I wonder what makes 6 get picked, so I run another command to choose from 2-6, it then just picks the 5.
[SBS96_selection_plot.pdf](https://github.com/AlexandrovLab/SigProfilerExtractor/files/11550246/SBS96_selection_plot.pdf)

In this case, which number should I use? Thank you

Jia

**Comment by mdbarnesUCSD** [comment]
Hi @bakeronit,

The automated selection of the number of signatures is done using the average and minimum stabilities (this is explained in the most recent manuscript [Islam et al. 2022 Cell Genomics](https://www.cell.com/cell-genomics/pdf/S2666-979X(22)00124-0.pdf)). It may help to look at the all_solutions_stat.csv file to better understand why one solution was selected over another. Some variation can be expected between different runs because of randomness. If you increase the number of replicates it may help provide consistency across different runs.

**Comment by mdbarnesUCSD** [comment]
Please reach out if you have any additional questions.
