### ISSUE TITLE
Denovo Signature and Assigning Signature Matching Error

### ISSUE THREAD

**Issue by KANGseungseok** [AlexandrovLab/SigProfilerExtractor#234]
Hello, I am a student studying bioinformatics.

I am encountering an error while using SigProfilerExtractor and am posting an issue here.

I generated 1 denovo signature and decomposed it against COSMIC v.3.4, which indicated the presence of SBS5 and SBS21. However, the columns in 'COSMIC_SBS96_Activities.txt' file are labeled as SBS1, SBS5, and SBS96A. How can this error be resolved?

I am attaching an image.

Thank you.

![image](https://github.com/AlexandrovLab/SigProfilerExtractor/assets/111939069/b7d8ceb8-7a06-404e-99fc-5b5285c8f31d)
![image](https://github.com/AlexandrovLab/SigProfilerExtractor/assets/111939069/acd1e55b-00b4-41ff-b549-0c61b91b8868)

**Comment by mdbarnesUCSD** [comment]
Hi @KANGseungseok,

The de novo signature SBS96A is present because it was not accurately reconstructed (cosine similarity was less than 0.8) with the COSMIC signatures. You can read more about this in the following posts:
https://github.com/AlexandrovLab/SigProfilerExtractor/issues/128
https://github.com/AlexandrovLab/SigProfilerExtractor/issues/171

Importantly, this analysis is not recommended on samples that have total mutations counts of 2 to 4. The resulting analysis will be highly inaccurate due to the reconstruction that is performed. It may help to check the reconstructed samples, these can be found in the `Solutions_Stats` folder, and filter out samples that were poorly reconstructed (ie. reconstructed samples that have less than 0.9 cosine similarity).

Please reach out if you have any additional questions.

Thanks!
