### ISSUE TITLE
CPU usage and GPU usage too little, and parameters don't take effect

### ISSUE THREAD

**Issue by xiaoyaojianghuzai** [AlexandrovLab/SigProfilerExtractor#243]
hi, professor @mdbarnesUCSD 
I run the code in linux for 700 vcf files
```python
sig.sigProfilerExtractor("vcf","example_output/rectum", "/mnt/h/tcgadata/rectum/input", "GRCh38", cpu=8, gpu=True,context_type= "SBS96,DBS78" , min_nmf_iterations= 1, max_nmf_iterations=2,batch_size=32)

```
then i  look at the usage of CPU and GPU
CPU is 20% usage and GPU is even 0. The cuda is correct and there is no warnings and mitakes.
how can I change the code to increase the speed by increasing the usage of CPU and GPU

**Comment by mdbarnesUCSD** [comment]
Hi @xiaoyaojianghuzai,

The min_nmf_iterations and max_nmf iterations that you are setting is are the bounds for how many iterations each replicate will be updated. Here are the default parameters:

- min_nmf_iterations= 10000
- max_nmf_iterations=1000000

The values that you set are very small to the point where minimal compute is being used so you are likely not seeing high CPU or GPU usage because of this.
