### ISSUE TITLE
Understanding the output

### ISSUE THREAD

**Issue by cagaser** [AlexandrovLab/SigProfilerExtractor#34]
Hello Developers, 

I am trying to understand the output of this tool. 
Only SBS96 were extracted from my data. 
Within the ```All_solutions``` directory are the 8 sub folders (SBS98_[1-8]_signatures). 

In SBS96_1, I see signature A. 
In SBS96_2, I see signature A and B
...
In SBS_8, I see signatures A-H

What is the purpose of having 1-8 folders and the A-H signatures? 
Furthermore, why is stability and the total number of mutations changes?
Which signature should I use for ```decompose``` function? 

Thank you in advance.

**Comment by mishugeb** [comment]
Please refer to the wiki page of the tool to understand the output: https://osf.io/t6j7u/wiki/3.%20Using%20the%20Tool%20-%20Output/

**Comment by cagaser** [comment]
Hello @mishugeb, 

Thank you for the reply. Perhaps the title of my issue was too short, apologies for that. 
As I mentioned before, I don't understand the signatures 1-8 and A-H. Of course, I've read the wiki page. However, I didn't see anything that clarifies my question about the signatures.

**Comment by mishugeb** [comment]
When you run an extraction SigProfilerExtractor extracts the different number of signatures between the range of your minimum_signatures and maximum_signatures parameters. In the ALL_Solutions you get the solutions for all possible signatures numbers the tool extracts. That's why you see the 1-8 signatures solution. In each solution folder, you will see information on the signatures named with alpha characters.

**Comment by cagaser** [comment]
Thank you very much!
