### ISSUE TITLE
Extractor with vcf not using all samples

### ISSUE THREAD

**Issue by julieefeusier** [AlexandrovLab/SigProfilerExtractor#71]
Hi,

I ran the newest version of SigProfilerExtractor either with a matrix file or with a directory of vcfs with the same options:
 (reference_genome="GRCh38", opportunity_genome="GRCh38", minimum_signatures=1, nmf_replicates=100, exome=true). I got wildly different numbers of signatures. I had 351 individuals in the matrix file and vcf directory. When I looked into the JOBMETADATA.txt, the matrix run used all 351 individuals. The vcf run used only 216 individuals (in alphabetical order, although skipped 17 in a row for some reason) for SBS96 and ID83, and 146 individuals for DBS78. Is that expected?

Also, I tried using cosmic_version=3.2, and it didn't work. Thanks!

**Comment by ntbeileh** [comment]
Hi,

Could you share your JOBMETADATA.txt for both the vcf and matrix runs so I can look into the issue?

**Comment by julieefeusier** [comment]
[VCF_JOB_METADATA.txt](https://github.com/AlexandrovLab/SigProfilerExtractor/files/6273447/VCF_JOB_METADATA.txt)
[Matrix_JOB_METADATA.txt](https://github.com/AlexandrovLab/SigProfilerExtractor/files/6273448/Matrix_JOB_METADATA.txt)

Here are the files. I realized that the opportunity genome for the matrix is still GRCh37, so I'm currently rerunning that right now. It did run all 351 samples, though. The VCF directory contains 351 vcf files. Thanks!

**Comment by ntbeileh** [comment]
You have the expected output for both the VCF and the matrix input.

When running with the exome = True option, SigProfilerExtractor limits its analysis to mutations within the exome. For VCF ​input, when this is the case some samples end up not having any mutations within the exome from a given category of mutations whether it be SBS96, ID83, or DBS78. So for example, the 216 samples you see for SBS96 are the samples that had SBS96 mutations within the exome.

Unlike a VCF input, the positional information of the mutations in the genome is not contained within the matrix input. So with a matrix as input, SigProfilerExtractor doesn't limit the analysis of mutations to just those within the exome because the positional information of those mutations isn't there. So it counts all mutations in its analysis.

**Comment by julieefeusier** [comment]
I don't know if that's the case here with the VCF files. After I created this issue, I was able to run all of the samples correctly using the tool SigProfilerSingleSample. I also changed the start of the VCF file names from numbers to letters and the matrix changed to 96x206! I stopped that analysis. I think at this point, I'm going to stick with the COSMIC-decomposed only results based on the previous literature of my tumor type and my goals. Thank you for your help!
