### ISSUE TITLE
reference genome; please install tar

### ISSUE THREAD

**Issue by maringa780** [AlexandrovLab/SigProfilerExtractor#83]
I'm trying to install a reference genome on a windows 7 computer. I successfully installed wget but now, when I try the code below, I get "You do not have tar installed. Please install tar..." error. I've searched online for which tar software to install with no success. Please assist. Thank you.
`
>> from SigProfilerMatrixGenerator import install as genInstall
>> genInstall.install('GRCh38')`

**Comment by ntbeileh** [comment]
You need tar installed as a command line tool on your system in order to extract the reference genome. I am not familiar with Windows 7 but these links may help in doing that for a Windows system:
https://wiki.haskell.org/How_to_unpack_a_tar_file_in_Windows
http://gnuwin32.sourceforge.net/packages/gtar.htm
